package com.fyber.inneractive.sdk.network;

import com.ironsource.mediationsdk.logger.IronSourceError;
import com.maticoo.sdk.p405ad.utils.error.ErrorCode;
import io.bidmachine.protobuf.EventTypeExtended;
import java.util.HashMap;
import p989u0.EnumC44419d;

/* renamed from: com.fyber.inneractive.sdk.network.t */
/* loaded from: classes4.dex */
public enum EnumC14730t {
    VAST_ERROR_DVC_FAILURE(46),
    FMP_SDK_INIT_FAILED(62),
    VAST_COMPANION_FAILED_LOADING(70),
    VAST_COMPANION_INCOMPATIBLE_MIMETYPE(75),
    FMP_COMPANION_FAILED_LOADING(78),
    VAST_ERROR_INVALID_RESPONSE(301),
    VAST_ERROR_TOO_MANY_WRAPPERS(302),
    VAST_ERROR_NO_MEDIA_FILES(303),
    VAST_ERROR_NO_COMPATIBLE_MEDIA_FILE(304),
    VAST_ERROR_PRE_BUFFER_TIMEOUT(ErrorCode.CODE_SHOW_RESOURCE_ERROR),
    VAST_ERROR_BUFFER_TIMEOUT(307),
    VAST_ERROR_FAILED_PLAYING_MEDIA_FILE(308),
    VAST_ERROR_FAILED_PLAYING_ALL_MEDIA_FILES(311),
    VAST_ERROR_UNSECURE_URL(312),
    MRAID_ERROR_UNSECURE_CONTENT(313),
    VPAID_ERROR_UNSECURE_CONTENT(314),
    MRAID_VIDEO_HAS_NOT_STARTED_PLAYING_IN_A_TIMELY_FASHION(390),
    VAST_UNKNOWN_PLAYER_ERROR(399),
    NATIVE_ERROR_INVALID_NATIVE_RESPONSE(401),
    NATIVE_ERROR_MISSING_PUB_REQUIRED_FIELD(402),
    NATIVE_ERROR_MISMATCH_REQUIRED_ASSET_RESPONSE(404),
    NATIVE_ERROR_INVALID_REQUIRED_ASSET_DATA(405),
    NATIVE_ERROR_INVALID_OPTIONAL_ASSET_DATA(406),
    NATIVE_ERROR_INVALID_LINK_WEB_URL(407),
    NATIVE_ERROR_FAILED_LOAD_ASSET(410),
    NATIVE_ERROR_MISMATCH_OPTIONAL_ASSET_RESPONSE(411),
    NATIVE_ERROR_MISSING_PROTOCOL_REQUIRED_FIELD(412),
    NATIVE_ERROR_RECEIVED_VIDEO_BUT_NOT_SUPPORTED(413),
    NATIVE_ERROR_NO_VALID_URLS_FOR_CLICK(414),
    NATIVE_ERROR_SOME_INVALID_URLS_FOR_PROCESSED_CLICK(415),
    MRAID_AUTO_ACTION_DETECTED(501),
    INTERNAL_CONFIG_MISMATCH(601),
    FATAL_ADM_PARSING_ERROR(603),
    FATAL_ADM_MARKUP_FETCHING_ERROR(604),
    TOKEN_EXCEEDS_LIMIT(605),
    IGNITE_FLOW_MODE_NOT_COMPATIBLE(606),
    IGNITE_FLOW_FAILED_TO_START(607),
    IGNITE_FLOW_FAILED_TO_INSTALL_APP(612),
    IGNITE_FLOW_FAILED_TO_LOAD_WEBPAGE(613),
    FATAL_CONFIGURATION_ERROR(701),
    FATAL_FEATURES_CONFIG_ERROR(IronSourceError.ERROR_NT_LOAD_PLACEMENT_CAPPED),
    IA_AD_LOAD_FAILED(EventTypeExtended.EVENT_TYPE_EXTENDED_BURL_VALUE),
    IA_AD_EXPIRED(EventTypeExtended.EVENT_TYPE_EXTENDED_NURL_VALUE),
    IA_AD_DESTROYED_WITHOUT_SHOW(EventTypeExtended.EVENT_TYPE_EXTENDED_LURL_VALUE),
    IA_AD_FAILURE_DATA(850),
    CLICK_PARSING_FAILURE(991),
    MISSMATCH_SPOTID(992),
    FAILED_DNS(995),
    FETCH_TOKEN_DV_ERROR(1000),
    DV_ERROR_PHASE(1001),
    ODT_ENCRYPTION_EXCEPTION(EnumC44419d.ENCRYPTION_EXCEPTION.m3080b()),
    ODT_RAW_ONE_DT_ERROR(EnumC44419d.RAW_ONE_DT_ERROR.m3080b()),
    ODT_ONE_DT_PARSE_ERROR(EnumC44419d.ONE_DT_PARSE_ERROR.m3080b()),
    ODT_ONE_DT_AUTHENTICATION_ERROR(EnumC44419d.ONE_DT_AUTHENTICATION_ERROR.m3080b()),
    ODT_ONE_DT_BROADCAST_ERROR(EnumC44419d.ONE_DT_BROADCAST_ERROR.m3080b()),
    ODT_ONE_DT_REQUEST_ERROR(EnumC44419d.ONE_DT_REQUEST_ERROR.m3080b()),
    ODT_ONE_DT_GENERAL_ERROR(EnumC44419d.ONE_DT_GENERAL_ERROR.m3080b());
    
    private static final HashMap<Integer, EnumC14730t> sMap = new HashMap<>();
    int val;

    static {
        EnumC14730t[] values;
        for (EnumC14730t enumC14730t : values()) {
            sMap.put(Integer.valueOf(enumC14730t.val), enumC14730t);
        }
    }

    EnumC14730t(int i) {
        this.val = i;
    }

    /* renamed from: a */
    public static EnumC14730t m77670a(EnumC44419d enumC44419d) {
        return sMap.get(Integer.valueOf(enumC44419d.m3080b()));
    }
}
