package com.zeus.gmc.sdk.mobileads.columbus.common;

import com.zeus.gmc.sdk.mobileads.columbus.C32065R;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/* loaded from: classes8.dex */
public class Constants {
    public static final String ACCESS = "Access";
    public static final String ADID = "adid";
    public static final String BACKGROUND = "Background";
    public static final String CARD = "Card";
    public static final Map<Integer, String> CLICK_AREA;
    public static final String CLICK_AREA_IS_CTA = "click_area";
    public static final int CLICK_IS_CTA = 0;
    public static final int CLICK_IS_NOT_CTA = 1;
    public static final String COSDK_VERSION = "cosdkversion";
    public static final String CREATIVE_TYPE = "creativeType";
    public static final String CTA = "CTA";
    public static final String CUSTOM_REFERENCE_DATA = "";
    public static final String DEBUGGER_INTENT_DEBUG_OFF = "com.xiaomi.ad.intent.DEBUG_OFF";
    public static final String DEBUGGER_INTENT_DEBUG_ON = "com.xiaomi.ad.intent.DEBUG_ON";
    public static final String DEBUGGER_INTENT_STAGING_OFF = "com.xiaomi.ad.intent.STAGING_OFF";
    public static final String DEBUGGER_INTENT_STAGING_ON = "com.xiaomi.ad.intent.STAGING_ON";
    public static final String ENDCARD_INTERACTIVE_TIME = "interactiveTime";
    public static final String ENDCARD_LOAD_TIME = "loadTime";
    public static final String ENDCARD_SHOW_WAY = "endCardShowWay";
    public static final String ENDCARD_STYLE_ID = "endcardStyleId";
    public static final String END_CARD_URL = "EndCardUrl";
    public static final String ERROR_CODE = "errorcode";
    public static final String ERROR_INFO = "errorinfo";
    public static final String GET_WHEN = "getWhen";
    public static final String ICON = "Icon";
    public static final String IMAGE = "Image";
    public static final String KEY_CLIENT_INFO_IS_BASE64 = "isbase64";
    public static final String KEY_TRACK_CONFIG_KEY = "systemadsolution_globalnative";
    public static final String KEY_TRACK_CONFIG_KEY_STAGING = "systemadsolution_globalnativestaging";
    public static final String LOAD_TIME = "loadTime";
    public static final String LOAD_WHEN = "load_when";
    public static final String LOC_ADS = "loc_ads";
    public static final String MATERIAL_SIZE = "materialSize";
    public static final String MEDIA_APP_VERSION = "mediaappversion";
    public static final String MEDIA_EXP_IDS = "mediaExpIds";
    public static final String MSA_ADS = "msa_ads";
    public static final String MSA_VERSION = "msa_version";
    public static final String NETWORK_CONNECTIVITY_CHANGE = "android.net.conn.CONNECTIVITY_CHANGE";
    public static final String NETWORK_IS_UNAVAILABLE = "NETWORK_UNAVAILABLE";
    public static final String NETWORT = "netWork";
    public static final String QUERY = "query";
    public static final String REAL_TAGID = "realTagId";
    public static final String REQ_ADS = "req_ads";
    public static final String RSP_ADS = "rsp_ads";
    public static final String SDK_ADS = "sdk_ads";
    public static final String SELECTIONS = "selections";
    public static final String SOURCE = "source";
    public static final String SUMMARY = "Summary";
    public static final String TAG_ID = "tagid";
    public static final String TITLE = "Title";
    public static final int TYPE_IS_H5 = 2;
    public static final int TYPE_IS_IMG = 0;
    public static final int TYPE_IS_VIDEO = 1;
    public static final String UI_SHOW_TIMES = "uiShowTimes";
    public static final String URL = "url";
    public static final String VIDEO = "Video";
    public static final String VIDEO_STYLE_ID = "videoStyleId";

    static {
        ConcurrentHashMap concurrentHashMap = new ConcurrentHashMap();
        CLICK_AREA = concurrentHashMap;
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.iv_learn_more), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.rl_normal_learn_more), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.fl_video_container), BACKGROUND);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.iv_video_img), IMAGE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.fl_img_end), IMAGE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.fl_img_end_1), IMAGE);
        int i = C32065R.C32068id.iv_app_icon;
        concurrentHashMap.put(Integer.valueOf(i), "Icon");
        int i2 = C32065R.C32068id.btn_install;
        concurrentHashMap.put(Integer.valueOf(i2), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_title), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_desc), SUMMARY);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.ll_content_end), BACKGROUND);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.iv_app_icon_end), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.btn_install_end), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.ll_content_end_landscape), BACKGROUND);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.iv_app_icon_end_landscape), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.fl_img_landscape), IMAGE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.btn_install_end_landscape), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_title_landscape), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_desc_landscape), SUMMARY);
        int i3 = C32065R.C32068id.iv_app_icon_details;
        concurrentHashMap.put(Integer.valueOf(i3), "Icon");
        int i4 = C32065R.C32068id.btn_install_details;
        concurrentHashMap.put(Integer.valueOf(i4), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_title_details), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_desc_details), SUMMARY);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.iv_app_icon_land_details), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.btn_install_land_details), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_title_land_details), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.tv_app_desc_land_details), SUMMARY);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.rl_click_area), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.rl_click_area_land_details), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.rl_install_land), CTA);
        concurrentHashMap.put(Integer.valueOf(i3), "Icon");
        concurrentHashMap.put(Integer.valueOf(i4), CTA);
        concurrentHashMap.put(Integer.valueOf(i), "Icon");
        concurrentHashMap.put(Integer.valueOf(i2), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_player_container), BACKGROUND);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_access), ACCESS);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_card), CARD);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_icon), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_title), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_cta), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_icon_other), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_summary_other), SUMMARY);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_reward_style_endcard_container), BACKGROUND);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_icon), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_img), IMAGE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_title), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_summary), SUMMARY);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_cta), CTA);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_icon_other), "Icon");
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_title_other), TITLE);
        concurrentHashMap.put(Integer.valueOf(C32065R.C32068id.columbus_end_card_summary_other), SUMMARY);
    }
}
