package com.maticoo.sdk.p405ad.utils.error;

import android.util.SparseArray;

/* renamed from: com.maticoo.sdk.ad.utils.error.ErrorCode */
/* loaded from: classes6.dex */
public class ErrorCode {
    public static final int CODE_BID_INTERNAL_ERROR = 406;
    public static final int CODE_BID_NETWORK_ERROR = 402;
    public static final int CODE_BID_SDK_NOT_INIT = 401;
    public static final int CODE_LOAD_BEFORE_UNKNOWN_ERROR = 217;
    public static final int CODE_LOAD_DESTROYED = 220;
    public static final int CODE_LOAD_DOWNLOAD_EXCEPTION = 214;
    public static final int CODE_LOAD_DOWNLOAD_FAILED = 213;
    public static final int CODE_LOAD_DOWNLOAD_ICON_FAILED = 222;
    public static final int CODE_LOAD_FREQUENCY_ERROR = 206;
    public static final int CODE_LOAD_FREQUENT_REQUEST_EXCEPTION = 223;
    public static final int CODE_LOAD_GDPR_REFUSE = 202;
    public static final int CODE_LOAD_LOADING = 407;
    public static final int CODE_LOAD_NETWORK_ERROR = 207;
    public static final int CODE_LOAD_NOT_INITIALIZED = 201;
    public static final int CODE_LOAD_NO_FILL = 209;
    public static final int CODE_LOAD_PARSE_FAILED = 211;
    public static final int CODE_LOAD_PLACEMENT_AD_TYPE_INCORRECT = 205;
    public static final int CODE_LOAD_PLACEMENT_EMPTY = 203;
    public static final int CODE_LOAD_PLACEMENT_IS_SHOWING = 215;
    public static final int CODE_LOAD_PLACEMENT_NOT_FOUND = 204;
    public static final int CODE_LOAD_RENDER_ERROR = 412;
    public static final int CODE_LOAD_RENDER_TIMEOUT = 410;
    public static final int CODE_LOAD_RENDER_UNKNOWN_EXCEPTION = 221;
    public static final int CODE_LOAD_RESOURCE_ERROR = 216;
    public static final int CODE_LOAD_SERVER_ERROR = 208;
    public static final int CODE_LOAD_TIMEOUT = 210;
    public static final int CODE_LOAD_UNKNOWN_ACTIVITY = 219;
    public static final int CODE_LOAD_UNKNOWN_EXCEPTION = 212;
    public static final int CODE_NO_RELOAD = 414;
    public static final int CODE_PRELOAD_ERROR = 416;
    public static final int CODE_REQ_LIMIT_EXCEEDED = 409;
    public static final int CODE_SHOW_CHECK_FAIL = 313;
    public static final int CODE_SHOW_CONTAINER_INVALID = 310;
    public static final int CODE_SHOW_EXPIRE_ERROR = 415;
    public static final int CODE_SHOW_FAIL_NOT_READY = 305;
    public static final int CODE_SHOW_INVALID_ARGUMENT = 308;
    public static final int CODE_SHOW_NOT_INITIALIZED = 304;
    public static final int CODE_SHOW_PAGE_FAIL = 311;
    public static final int CODE_SHOW_PLACEMENT_AD_TYPE_INCORRECT = 303;
    public static final int CODE_SHOW_PLACEMENT_EMPTY = 301;
    public static final int CODE_SHOW_PLACEMENT_NOT_FOUND = 302;
    public static final int CODE_SHOW_RENDER_ERROR = 413;
    public static final int CODE_SHOW_RENDER_PROCESS_GONE = 312;
    public static final int CODE_SHOW_RESOURCE_ERROR = 306;
    public static final int CODE_SHOW_SHOWING = 408;
    public static final int CODE_SHOW_TIMEOUT = 309;
    public static final int CODE_SHOW_UNKNOWN_EXCEPTION = 307;
    private static final String MSG_BID_INTERNAL_ERROR = "Internal Error";
    private static final String MSG_BID_SDK_NETWORK = "Network is currently unavailable";
    private static final String MSG_BID_SDK_NOT_INIT = "SDK Uninitialized";
    private static final String MSG_LOAD_BEFORE_UNKNOWN_ERROR = "Load failed: unknown exception occurred";
    private static final String MSG_LOAD_DESTROYED = "Load failed: ad config destroy";
    private static final String MSG_LOAD_DOWNLOAD_EXCEPTION = "Load failed: unknown exception occurred";
    private static final String MSG_LOAD_DOWNLOAD_FAILED = "Load failed: assets download failed";
    private static final String MSG_LOAD_DOWNLOAD_ICON_FAILED = "Load failed: download icon failed";
    private static final String MSG_LOAD_FREQUENCY_ERROR = "Load failed: no ad fill";
    private static final String MSG_LOAD_FREQUENT_REQUEST_EXCEPTION = "Load failed: Current frequent request exceptions";
    private static final String MSG_LOAD_GDPR_REFUSE = "Load failed: GDPR refuse";
    private static final String MSG_LOAD_LOADING = "Load failed: ad is loading";
    private static final String MSG_LOAD_NETWORK_ERROR = "Load failed: network error";
    private static final String MSG_LOAD_NOT_INITIALIZED = "Load failed: SDK not initialized";
    private static final String MSG_LOAD_NO_FILL = "Load failed: no ad fill";
    private static final String MSG_LOAD_PARSE_FAILED = "Load failed: data parsing failed";
    private static final String MSG_LOAD_PLACEMENT_AD_TYPE_INCORRECT = "Load failed: ad type wrong";
    private static final String MSG_LOAD_PLACEMENT_EMPTY = "Load failed: placement is empty";
    private static final String MSG_LOAD_PLACEMENT_IS_SHOWING = "Load failed: placement is showing";
    private static final String MSG_LOAD_PLACEMENT_NOT_FOUND = "Load failed: Placement not found in app";
    private static final String MSG_LOAD_RENDER_ERROR = "Load failed: WebViewReceivedError error";
    private static final String MSG_LOAD_RENDER_TIMEOUT = "Load failed: WebView load timeout";
    private static final String MSG_LOAD_RENDER_UNKNOWN_EXCEPTION = "Load failed: render ad unknown exception occurred";
    private static final String MSG_LOAD_RESOURCE_ERROR = "Load failed: resource error";
    private static final String MSG_LOAD_SERVER_ERROR = "Load failed: server error";
    private static final String MSG_LOAD_TIMEOUT = "Load failed: load ad timeout";
    private static final String MSG_LOAD_UNKNOWN_ACTIVITY = "Load failed: activity is unknown";
    private static final String MSG_LOAD_UNKNOWN_EXCEPTION = "Load failed: unknown exception occurred";
    private static final String MSG_NO_RELOAD = "Load failed: no reload, mraid expand";
    private static final String MSG_PRELOAD_ERROR = "Preload failed: video resource access error";
    private static final String MSG_REQ_LIMIT_EXCEEDED = "Show failed: Request limit exceeded";
    public static final String MSG_SHOW_CHECK_FAIL = "Show failed: callback check fail.";
    public static final String MSG_SHOW_CONTAINER_INVALID = "Show failed: Ad Container is invalid, ";
    private static final String MSG_SHOW_EXPIRE_ERROR = "Show failed: ad expire";
    private static final String MSG_SHOW_FAIL_NOT_READY = "Show failed: ad not ready";
    public static final String MSG_SHOW_INVALID_ARGUMENT = "Show failed: Invalid Argument, ";
    private static final String MSG_SHOW_NOT_INITIALIZED = "Show failed: SDK not initialized";
    public static final String MSG_SHOW_PAGE_FAIL = "Show failed: show page fail.";
    private static final String MSG_SHOW_PLACEMENT_AD_TYPE_INCORRECT = "Show failed: adtype wrong";
    private static final String MSG_SHOW_PLACEMENT_EMPTY = "Show failed: placement empty";
    private static final String MSG_SHOW_PLACEMENT_NOT_FOUND = "Show failed: placement not found in app";
    private static final String MSG_SHOW_RENDER_ERROR = "Show failed: WebViewReceivedError error";
    public static final String MSG_SHOW_RENDER_PROCESS_GONE = "Show failed: callback Render Process Gone.";
    private static final String MSG_SHOW_RESOURCE_ERROR = "Show failed: resource not ready";
    private static final String MSG_SHOW_SHOWING = "Show failed: ad is showing";
    public static final String MSG_SHOW_TIMEOUT = "Show failed: Display ad timeout, ";
    private static final String MSG_SHOW_UNKNOWN_EXCEPTION = "Show failed: unknown exception occurred";
    private static final SparseArray<String> mErrorMap;

    static {
        SparseArray<String> sparseArray = new SparseArray<>();
        mErrorMap = sparseArray;
        sparseArray.put(201, MSG_LOAD_NOT_INITIALIZED);
        sparseArray.put(202, MSG_LOAD_GDPR_REFUSE);
        sparseArray.put(203, MSG_LOAD_PLACEMENT_EMPTY);
        sparseArray.put(204, MSG_LOAD_PLACEMENT_NOT_FOUND);
        sparseArray.put(205, MSG_LOAD_PLACEMENT_AD_TYPE_INCORRECT);
        sparseArray.put(206, "Load failed: no ad fill");
        sparseArray.put(207, MSG_LOAD_NETWORK_ERROR);
        sparseArray.put(208, MSG_LOAD_SERVER_ERROR);
        sparseArray.put(209, "Load failed: no ad fill");
        sparseArray.put(210, MSG_LOAD_TIMEOUT);
        sparseArray.put(211, MSG_LOAD_PARSE_FAILED);
        sparseArray.put(212, "Load failed: unknown exception occurred");
        sparseArray.put(213, MSG_LOAD_DOWNLOAD_FAILED);
        sparseArray.put(214, "Load failed: unknown exception occurred");
        sparseArray.put(215, MSG_LOAD_PLACEMENT_IS_SHOWING);
        sparseArray.put(216, MSG_LOAD_RESOURCE_ERROR);
        sparseArray.put(217, "Load failed: unknown exception occurred");
        sparseArray.put(219, MSG_LOAD_UNKNOWN_ACTIVITY);
        sparseArray.put(220, MSG_LOAD_DESTROYED);
        sparseArray.put(221, MSG_LOAD_RENDER_UNKNOWN_EXCEPTION);
        sparseArray.put(213, MSG_LOAD_DOWNLOAD_FAILED);
        sparseArray.put(222, MSG_LOAD_DOWNLOAD_ICON_FAILED);
        sparseArray.put(223, MSG_LOAD_FREQUENT_REQUEST_EXCEPTION);
        sparseArray.put(214, "Load failed: unknown exception occurred");
        sparseArray.put(301, MSG_SHOW_PLACEMENT_EMPTY);
        sparseArray.put(302, MSG_SHOW_PLACEMENT_NOT_FOUND);
        sparseArray.put(303, MSG_SHOW_PLACEMENT_AD_TYPE_INCORRECT);
        sparseArray.put(304, MSG_SHOW_NOT_INITIALIZED);
        sparseArray.put(305, MSG_SHOW_FAIL_NOT_READY);
        sparseArray.put(CODE_SHOW_RESOURCE_ERROR, MSG_SHOW_RESOURCE_ERROR);
        sparseArray.put(307, MSG_SHOW_UNKNOWN_EXCEPTION);
        sparseArray.put(308, MSG_SHOW_INVALID_ARGUMENT);
        sparseArray.put(309, MSG_SHOW_TIMEOUT);
        sparseArray.put(310, MSG_SHOW_CONTAINER_INVALID);
        sparseArray.put(311, MSG_SHOW_PAGE_FAIL);
        sparseArray.put(312, MSG_SHOW_RENDER_PROCESS_GONE);
        sparseArray.put(313, MSG_SHOW_CHECK_FAIL);
        sparseArray.put(401, MSG_BID_SDK_NOT_INIT);
        sparseArray.put(402, MSG_BID_SDK_NETWORK);
        sparseArray.put(406, MSG_BID_INTERNAL_ERROR);
        sparseArray.put(407, MSG_LOAD_LOADING);
        sparseArray.put(408, MSG_SHOW_SHOWING);
        sparseArray.put(409, MSG_REQ_LIMIT_EXCEEDED);
        sparseArray.put(410, MSG_LOAD_RENDER_TIMEOUT);
        sparseArray.put(412, MSG_LOAD_RENDER_ERROR);
        sparseArray.put(413, MSG_SHOW_RENDER_ERROR);
        sparseArray.put(414, MSG_NO_RELOAD);
        sparseArray.put(415, MSG_SHOW_EXPIRE_ERROR);
        sparseArray.put(416, MSG_PRELOAD_ERROR);
    }

    /* JADX INFO: Access modifiers changed from: package-private */
    public static String getErrorMessage(int i) {
        return mErrorMap.get(i);
    }
}
