package com.maticoo.sdk.utils.lifecycle;

import android.util.Base64;
import java.nio.charset.Charset;

/* loaded from: classes6.dex */
public class TypeConstant {
    static final String[] ADS_ACT = {new String(Base64.decode("Y29tLmdvb2dsZS5hbmRyb2lkLmdtcy5hZHM=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmZhY2Vib29rLmFkcw==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLnVuaXR5M2Quc2VydmljZXMuYWRz", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLnZ1bmdsZQ==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmFkY29sb255", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmFwcGxvdmlu", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLm1vcHVi", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLnRhcGpveQ==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmNoYXJ0Ym9vc3Q=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmJ5dGVkYW5jZS5zZGs=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmlyb25zb3VyY2Uuc2RrLmNvbnRyb2xsZXI=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLm15LnRhcmdldA==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLm1icmlkZ2UubXNkay4=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmNoYXJ0Ym9vc3RfaGVsaXVtLnNkaw==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLnFxLmUuYWRz", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLnNpZ21vYi53aW5kYWQ=", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmt3YWQuc2RrLmFwaS5wcm94eQ==", 2), Charset.forName("UTF-8")), new String(Base64.decode("aW8ucHJlc2FnZS5pbnRlcnN0aXRpYWwudWk=", 2), Charset.forName("UTF-8")), new String(Base64.decode("bmV0LnB1Ym5hdGl2ZS5saXRlLnNkaw==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmNyb3NzcHJvbW90aW9uLnNkay4=", 2), Charset.forName("UTF-8")), new String(Base64.decode("YWRtb3N0LnNkay4=", 2), Charset.forName("UTF-8")), new String(Base64.decode("YWRtb3N0LmFkc2VydmVyLg==", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmZsYXRhZHMuc2RrLnVp", 2), Charset.forName("UTF-8")), new String(Base64.decode("Y29tLmlubW9iaS5hZHMucmVuZGVyaW5n", 2), Charset.forName("UTF-8"))};
}
